2025-04-14 15:08:24.947586: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-14 15:08:24.948210: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-14 15:08:24.951314: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-14 15:08:24.959979: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1744639704.974347    4719 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1744639704.978825    4719 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1744639704.989338    4719 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1744639704.989393    4719 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1744639704.989401    4719 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1744639704.989403    4719 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-04-14 15:08:24.992953: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/jmulvany/.local/lib/python3.10/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.26.0 is required for this version of SciPy (detected version 2.1.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/jmulvany/Thesis_BU/iv_VM/server_LDP.py", line 3, in <module>
    import tensorflow as tf
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/__init__.py", line 49, in <module>
    from tensorflow._api.v2 import __internal__
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/_api/v2/__internal__/__init__.py", line 13, in <module>
    from tensorflow._api.v2.__internal__ import feature_column
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/_api/v2/__internal__/feature_column/__init__.py", line 8, in <module>
    from tensorflow.python.feature_column.feature_column_v2 import DenseColumn # line: 1777
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 38, in <module>
    from tensorflow.python.feature_column import feature_column as fc_old
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/python/feature_column/feature_column.py", line 41, in <module>
    from tensorflow.python.layers import base
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/python/layers/base.py", line 16, in <module>
    from tensorflow.python.keras.legacy_tf_layers import base
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import models
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/python/keras/models.py", line 25, in <module>
    from tensorflow.python.keras.engine import training_v1
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/python/keras/engine/training_v1.py", line 46, in <module>
    from tensorflow.python.keras.engine import training_arrays_v1
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/python/keras/engine/training_arrays_v1.py", line 37, in <module>
    from scipy.sparse import issparse  # pylint: disable=g-import-not-at-top
  File "/home/jmulvany/.local/lib/python3.10/site-packages/scipy/sparse/__init__.py", line 267, in <module>
    from ._csr import *
  File "/home/jmulvany/.local/lib/python3.10/site-packages/scipy/sparse/_csr.py", line 10, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/jmulvany/Thesis_BU/iv_VM/server_LDP.py", line 3, in <module>
    import tensorflow as tf
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/__init__.py", line 49, in <module>
    from tensorflow._api.v2 import __internal__
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/_api/v2/__internal__/__init__.py", line 13, in <module>
    from tensorflow._api.v2.__internal__ import feature_column
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/_api/v2/__internal__/feature_column/__init__.py", line 8, in <module>
    from tensorflow.python.feature_column.feature_column_v2 import DenseColumn # line: 1777
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 38, in <module>
    from tensorflow.python.feature_column import feature_column as fc_old
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/python/feature_column/feature_column.py", line 41, in <module>
    from tensorflow.python.layers import base
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/python/layers/base.py", line 16, in <module>
    from tensorflow.python.keras.legacy_tf_layers import base
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import models
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/python/keras/models.py", line 25, in <module>
    from tensorflow.python.keras.engine import training_v1
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/python/keras/engine/training_v1.py", line 71, in <module>
    from scipy.sparse import issparse  # pylint: disable=g-import-not-at-top
  File "/home/jmulvany/.local/lib/python3.10/site-packages/scipy/sparse/__init__.py", line 267, in <module>
    from ._csr import *
  File "/home/jmulvany/.local/lib/python3.10/site-packages/scipy/sparse/_csr.py", line 10, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/home/jmulvany/Thesis_BU/iv_VM/server_LDP.py", line 3, in <module>
    import tensorflow as tf
  File "/home/jmulvany/.local/lib/python3.10/site-packages/tensorflow/__init__.py", line 468, in <module>
    importlib.import_module("keras.src.optimizers")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/__init__.py", line 2, in <module>
    from keras.api import DTypePolicy
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import activations
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/api/activations/__init__.py", line 7, in <module>
    from keras.src.activations import deserialize
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/src/__init__.py", line 1, in <module>
    from keras.src import activations
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/src/activations/__init__.py", line 33, in <module>
    from keras.src.saving import object_registration
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/src/saving/__init__.py", line 7, in <module>
    from keras.src.saving.saving_api import load_model
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/src/saving/saving_api.py", line 7, in <module>
    from keras.src.legacy.saving import legacy_h5_format
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/src/legacy/saving/legacy_h5_format.py", line 13, in <module>
    from keras.src.legacy.saving import saving_utils
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/src/legacy/saving/saving_utils.py", line 10, in <module>
    from keras.src import models
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/src/models/__init__.py", line 1, in <module>
    from keras.src.models.functional import Functional
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/src/models/functional.py", line 16, in <module>
    from keras.src.models.model import Model
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/src/models/model.py", line 12, in <module>
    from keras.src.trainers import trainer as base_trainer
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/src/trainers/trainer.py", line 14, in <module>
    from keras.src.trainers.data_adapters import data_adapter_utils
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/src/trainers/data_adapters/__init__.py", line 4, in <module>
    from keras.src.trainers.data_adapters import array_data_adapter
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/src/trainers/data_adapters/array_data_adapter.py", line 7, in <module>
    from keras.src.trainers.data_adapters import array_slicing
  File "/home/jmulvany/.local/lib/python3.10/site-packages/keras/src/trainers/data_adapters/array_slicing.py", line 12, in <module>
    import pandas
  File "/home/jmulvany/.local/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/home/jmulvany/.local/lib/python3.10/site-packages/pandas/compat/__init__.py", line 25, in <module>
    from pandas.compat.numpy import (
  File "/home/jmulvany/.local/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/jmulvany/.local/lib/python3.10/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/jmulvany/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/home/jmulvany/.local/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
